
package com.mycompany.mislibros.vista;

import com.mycompany.mislibros.modelo.Autor;
import com.mycompany.mislibros.controlador.Controladora;
import com.mycompany.mislibros.controlador.LogicaBuscarAutoresDeLibro;
import com.mycompany.mislibros.modelo.Libro;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martín_Guerra
 */
public class Principal extends javax.swing.JFrame {

    Controladora control;

    public Principal() {
        initComponents();
        //Cuando se abre la interfaz gráfica, se crea una instancia a la lógica.
        control = new Controladora();
        mostrarListaLibros();
        agregarTooltipALaTabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        btnEliminarActor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnIngresarLibro = new javax.swing.JButton();
        btnVerLibros = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnIngresarActor1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnEliminarActor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosss/16083460.png"))); // NOI18N
        btnEliminarActor.setText("Eliminar autor");
        btnEliminarActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActorActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jLabel2.setText("MI  BIBLIOTECA");

        btnIngresarLibro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnIngresarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosss/12088250.png"))); // NOI18N
        btnIngresarLibro.setText("Ingresar libro");
        btnIngresarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLibroActionPerformed(evt);
            }
        });

        btnVerLibros.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnVerLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosss/rotation-arrow-icon-png (1).png"))); // NOI18N
        btnVerLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerLibrosActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosss/3661280 (1).png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "titulo", "género", "n° páginas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaLibros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(tablaLibros);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosss/16083460.png"))); // NOI18N
        btnEliminar.setText("Eliminar libro");
        btnEliminar.setMaximumSize(new java.awt.Dimension(100, 23));
        btnEliminar.setMinimumSize(new java.awt.Dimension(100, 23));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnIngresarActor1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnIngresarActor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosss/business-avatar-icon-with-a-simple-clean-design-featuring-a-man-in-a-suit-suitable-for-online-profiles-or-websites-free-png (1).png"))); // NOI18N
        btnIngresarActor1.setText("Ingresar autor");
        btnIngresarActor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActor1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosss/3965105 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVerLibros)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIngresarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIngresarActor1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnIngresarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnIngresarActor1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVerLibros))
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnEliminarActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActorActionPerformed
        
    }//GEN-LAST:event_btnEliminarActorActionPerformed

    private void btnIngresarActor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActor1ActionPerformed
        // TODO add your handling code here:
        ventanaIngresarAutor ventIngAut= new ventanaIngresarAutor(control);
        ventIngAut.setVisible(true);
        ventIngAut.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarActor1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaLibros.getSelectedRow();

        if (filaSeleccionada >=0){

            int idLibro = (int) tablaLibros.getValueAt(filaSeleccionada, 0);

            int confirmarcion = JOptionPane.showConfirmDialog(this, "Va a eliminar el libro con id: " +idLibro + " ¿Esta seguro?", "Confirmar Eliminacion", JOptionPane.YES_NO_OPTION) ;

            if (confirmarcion == JOptionPane.YES_OPTION){
                control.eliminarLibro(idLibro);

                mostrarListaLibros();
                JOptionPane.showMessageDialog(this, "Libro eliminado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un libro para eliminar", "error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.out.println("Cerrando programa.....");
        System.exit(0); //cierra la aplicación
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVerLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLibrosActionPerformed
        mostrarListaLibros();
    }//GEN-LAST:event_btnVerLibrosActionPerformed

    private void btnIngresarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLibroActionPerformed
        ventanaIngresarLibro ventIngLib = new ventanaIngresarLibro(control);
        ventIngLib.setVisible(true);
        ventIngLib.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIngresarLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarActor;
    private javax.swing.JButton btnIngresarActor1;
    private javax.swing.JButton btnIngresarLibro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaLibros;
    // End of variables declaration//GEN-END:variables
    
    public void mostrarListaLibros(){
        DefaultTableModel modelo = (DefaultTableModel) tablaLibros.getModel();
        modelo.setRowCount(0);
        
        //Traigo la lista de libros de mi base de datos
        ArrayList<Libro> listaLibros = control.traerListaLibros();
        for (Libro libro : listaLibros) {
        modelo.addRow(new Object[]{
            libro.getId(),
            libro.getTitulo(),
            libro.getClasificacion(),
            libro.getNumero(),
            libro.obtenerCreadores()
        });
    }
    }
    //Este metodo muestra el autor al arrastrar el mouse sobre un libro
    private void agregarTooltipALaTabla(){
        tablaLibros.addMouseMotionListener(new java.awt.event.MouseMotionAdapter(){
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e){
            //Obtenemos la fila donde esta parado el mouse
            int fila = tablaLibros.rowAtPoint(e.getPoint());
            //Obtenemos la columna donde esta parado el mouse
            int columna = tablaLibros.columnAtPoint(e.getPoint());
            
            /*Verificamos si el mouse esta parado sobre un libro, de ser asi muestra un cuadro con el autor,
            Si no hay ningun libro, no muestra nada (Sin esto se mostraria la informacion fuera de la tabla)
            
            */
            if (fila > -1 && columna >1) {
                
                //Obtenemos el id que esta ubicado en la columna 0
                int idLibro = (int) tablaLibros.getValueAt(fila, 0); 
                
                //Traemos el objeto libro desde su id
                Libro libro = control.traerLibro(idLibro);
                
                //Si el libro existe, se mostrara su autor
                if(libro != null) {
                    //Usamos html para hacer un salto de linea a la hora de mostrar los autores(En caso de que haya mas de un autor)
                    tablaLibros.setToolTipText("<html><b> Autor:" + libro.obtenerCreadores());
                
                //Si no existe, no se mostrara nada
                } else {
                    tablaLibros.setToolTipText(null);
                }
                
            }
            
            
        }
        
        
    });
    
}
    
}
